format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$aws\
$gcloud\
$kubernetes\
$docker_context\
$package\
$c\
$elixir\
$golang\
$lua\
$nodejs\
$ocaml\
$python\
$rust\
$scala\
$swift\
$zig\
$cmd_duration $jobs $time\
$line_break\
$character"""

[fill]
symbol = " "

[username]
disabled = false
format = "[$user]($style) "

[hostname]
disabled = false
format = "[$hostname]($style) | "

[directory]
style = "white"
read_only = " 󰌾"
truncation_length = 4
truncate_to_repo = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](purple)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold blue"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\] '
symbol = " "

[c]
format = '\[[$symbol($version(-$name))]($style)\] '
symbol = " "

[docker_context]
format = '\[[$symbol$context]($style)\] '
symbol = " "

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\] '
symbol = " "

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\] '
symbol = " "

[golang]
format = '\[[$symbol($version)]($style)\] '
symbol = " "

[kubernetes]
format = '\[[$symbol$context( \($namespace\))]($style)\]'
symbol = " "

[lua]
format = '\[[$symbol($version)]($style)\] '
symbol = " "

[nodejs]
format = '\[[$symbol($version)]($style)\] '
symbol = " "

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\] '
symbol = " "

[package]
format = '\[[$symbol$version]($style)\] '
symbol = "󰏗 "

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\] '
symbol = " "

[rust]
format = '\[[$symbol($version)]($style)\] '
symbol = "󱘗 "

[scala]
format = '\[[$symbol($version)]($style)\] '
symbol = " "

[swift]
format = '\[[$symbol($version)]($style)\] '
symbol = " "

[zig]
format = '\[[$symbol($version)]($style)\] '
symbol = " "
